from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="About Me", max_length=160)),
                ("greeting", models.CharField(default="Hello!", max_length=160)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
            ],
            options={"verbose_name": "About", "verbose_name_plural": "About", "ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("author", models.CharField(blank=True, max_length=120)),
                ("date", models.CharField(blank=True, max_length=80)),
                ("duration", models.CharField(blank=True, max_length=80)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/")),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("issuer", models.CharField(blank=True, max_length=160)),
                ("credential", models.CharField(default="Certificate", max_length=160)),
                ("credential_id", models.CharField(blank=True, max_length=160)),
                ("period", models.CharField(blank=True, max_length=80)),
                ("issue_date", models.CharField(blank=True, max_length=80)),
                ("image", models.ImageField(blank=True, null=True, upload_to="certificates/")),
                ("verify_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Contact", max_length=160)),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={"verbose_name": "Contact", "verbose_name_plural": "Contact", "ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("degree", models.CharField(max_length=180)),
                ("school", models.CharField(max_length=180)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("period", models.CharField(blank=True, max_length=160)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=160)),
                ("company", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("period", models.CharField(blank=True, max_length=160)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("copyright_text", models.CharField(max_length=255)),
                ("design_by_text", models.CharField(blank=True, max_length=120)),
                ("design_by_url", models.URLField(blank=True)),
            ],
            options={"verbose_name": "Footer", "verbose_name_plural": "Footer", "ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("role", models.CharField(max_length=160)),
                ("headline_name", models.CharField(blank=True, max_length=160)),
                ("headline_role", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="hero/")),
                ("cv_file", models.FileField(blank=True, null=True, upload_to="hero/files/")),
                ("cv_url", models.URLField(blank=True)),
            ],
            options={"verbose_name": "Hero", "verbose_name_plural": "Hero", "ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("details", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="projects/")),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="HeroInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=255)),
                ("hero", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="info_items", to="portfolio.hero")),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="HeroStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=120)),
                ("hero", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stats", to="portfolio.hero")),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="EssentialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=80)),
                ("url", models.URLField(blank=True)),
                ("icon", models.CharField(help_text="Example: github, linkedin, leetcode, codeforces", max_length=80)),
                ("color", models.CharField(default="#12F7D6", max_length=20)),
                ("hero", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="essential_links", to="portfolio.hero")),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("icon_name", models.CharField(blank=True, help_text="Simple Icons slug, e.g. django, react", max_length=80)),
                ("icon_image", models.ImageField(blank=True, null=True, upload_to="skills/icons/")),
                ("color", models.CharField(default="#12F7D6", max_length=20)),
                ("fallback", models.CharField(blank=True, max_length=12)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skills", to="portfolio.skillgroup")),
            ],
            options={"ordering": ["order", "id"]},
        ),
    ]
